[2023-12-04T11:45:16.376+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fantasy_premier_league_debug.move_file_into_archive_folder_test scheduled__2023-12-03T03:44:51.910374+00:00 [queued]>
[2023-12-04T11:45:16.394+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fantasy_premier_league_debug.move_file_into_archive_folder_test scheduled__2023-12-03T03:44:51.910374+00:00 [queued]>
[2023-12-04T11:45:16.395+0800] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-04T11:45:16.447+0800] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): move_file_into_archive_folder_test> on 2023-12-03 03:44:51.910374+00:00
[2023-12-04T11:45:16.453+0800] {standard_task_runner.py:57} INFO - Started process 18811 to run task
[2023-12-04T11:45:16.464+0800] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'fantasy_premier_league_debug', 'move_file_into_archive_folder_test', 'scheduled__2023-12-03T03:44:51.910374+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/azfar_dag.py', '--cfg-path', '/tmp/tmp35mvqqlk']
[2023-12-04T11:45:16.467+0800] {standard_task_runner.py:85} INFO - Job 126: Subtask move_file_into_archive_folder_test
[2023-12-04T11:45:16.547+0800] {task_command.py:416} INFO - Running <TaskInstance: fantasy_premier_league_debug.move_file_into_archive_folder_test scheduled__2023-12-03T03:44:51.910374+00:00 [running]> on host azfartitu.
[2023-12-04T11:45:16.675+0800] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fantasy_premier_league_debug' AIRFLOW_CTX_TASK_ID='move_file_into_archive_folder_test' AIRFLOW_CTX_EXECUTION_DATE='2023-12-03T03:44:51.910374+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-03T03:44:51.910374+00:00'
[2023-12-04T11:45:16.688+0800] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/azfarmustafa/airflow_tutorial/dags/azfar_dag.py", line 60, in move_file_into_archive_folder_test
    formatted_current_date = formatted_current_dates[0]
TypeError: 'NoneType' object is not subscriptable
[2023-12-04T11:45:16.698+0800] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fantasy_premier_league_debug, task_id=move_file_into_archive_folder_test, execution_date=20231203T034451, start_date=20231204T034516, end_date=20231204T034516
[2023-12-04T11:45:16.728+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 126 for task move_file_into_archive_folder_test ('NoneType' object is not subscriptable; 18811)
[2023-12-04T11:45:16.759+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-04T11:45:16.793+0800] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
