[2023-12-22T15:57:21.773+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fantasy_premier_league_debug.get_old_date_test manual__2023-12-22T07:57:18.317546+00:00 [queued]>
[2023-12-22T15:57:21.782+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fantasy_premier_league_debug.get_old_date_test manual__2023-12-22T07:57:18.317546+00:00 [queued]>
[2023-12-22T15:57:21.782+0800] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-22T15:57:21.801+0800] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): get_old_date_test> on 2023-12-22 07:57:18.317546+00:00
[2023-12-22T15:57:21.804+0800] {standard_task_runner.py:57} INFO - Started process 107637 to run task
[2023-12-22T15:57:21.809+0800] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'fantasy_premier_league_debug', 'get_old_date_test', 'manual__2023-12-22T07:57:18.317546+00:00', '--job-id', '215', '--raw', '--subdir', 'DAGS_FOLDER/azfar_dag.py', '--cfg-path', '/tmp/tmpskwy1gtl']
[2023-12-22T15:57:21.810+0800] {standard_task_runner.py:85} INFO - Job 215: Subtask get_old_date_test
[2023-12-22T15:57:21.847+0800] {task_command.py:416} INFO - Running <TaskInstance: fantasy_premier_league_debug.get_old_date_test manual__2023-12-22T07:57:18.317546+00:00 [running]> on host azfartitu.
[2023-12-22T15:57:21.918+0800] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fantasy_premier_league_debug' AIRFLOW_CTX_TASK_ID='get_old_date_test' AIRFLOW_CTX_EXECUTION_DATE='2023-12-22T07:57:18.317546+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-22T07:57:18.317546+00:00'
[2023-12-22T15:57:21.925+0800] {base.py:73} INFO - Using connection ID 'azure_blob_conn_id' for task execution.
[2023-12-22T15:57:23.009+0800] {logging_mixin.py:154} INFO - ['current_season_history', 'current_season_history/current', 'current_season_history/current/11122023', 'current_season_history/current/11122023/current_season_history_11122023.parquet', 'player_metadata', 'player_metadata/current', 'player_metadata/current/11122023', 'player_metadata/current/11122023/player_metadata_11122023.parquet', 'position_metadata', 'position_metadata/current', 'position_metadata/current/11122023', 'position_metadata/current/11122023/position_metadata_11122023.parquet', 'teams_metadata', 'teams_metadata/current', 'teams_metadata/current/11122023', 'teams_metadata/current/11122023/teams_metadata_11122023.parquet']
[2023-12-22T15:57:23.009+0800] {logging_mixin.py:154} INFO - ['current_season_history']
[2023-12-22T15:57:23.009+0800] {logging_mixin.py:154} INFO - ['current_season_history', 'current']
[2023-12-22T15:57:23.009+0800] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/azfarmustafa/airflow_tutorial/dags/azfar_dag.py", line 45, in get_old_date_test
    if len(parts) > 1 and parts[2].isdigit():
IndexError: list index out of range
[2023-12-22T15:57:23.013+0800] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fantasy_premier_league_debug, task_id=get_old_date_test, execution_date=20231222T075718, start_date=20231222T075721, end_date=20231222T075723
[2023-12-22T15:57:23.035+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 215 for task get_old_date_test (list index out of range; 107637)
[2023-12-22T15:57:23.067+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-22T15:57:23.092+0800] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
