[2023-11-29T23:36:29.318+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fantasy_premier_league_debug.move_file_into_archive_folder manual__2023-11-29T15:36:25.627083+00:00 [queued]>
[2023-11-29T23:36:29.328+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fantasy_premier_league_debug.move_file_into_archive_folder manual__2023-11-29T15:36:25.627083+00:00 [queued]>
[2023-11-29T23:36:29.328+0800] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-29T23:36:29.353+0800] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): move_file_into_archive_folder> on 2023-11-29 15:36:25.627083+00:00
[2023-11-29T23:36:29.358+0800] {standard_task_runner.py:57} INFO - Started process 24342 to run task
[2023-11-29T23:36:29.361+0800] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'fantasy_premier_league_debug', 'move_file_into_archive_folder', 'manual__2023-11-29T15:36:25.627083+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/azfar_dag.py', '--cfg-path', '/tmp/tmpnxq22z56']
[2023-11-29T23:36:29.363+0800] {standard_task_runner.py:85} INFO - Job 28: Subtask move_file_into_archive_folder
[2023-11-29T23:36:29.413+0800] {task_command.py:416} INFO - Running <TaskInstance: fantasy_premier_league_debug.move_file_into_archive_folder manual__2023-11-29T15:36:25.627083+00:00 [running]> on host azfartitu.
[2023-11-29T23:36:29.507+0800] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fantasy_premier_league_debug' AIRFLOW_CTX_TASK_ID='move_file_into_archive_folder' AIRFLOW_CTX_EXECUTION_DATE='2023-11-29T15:36:25.627083+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-29T15:36:25.627083+00:00'
[2023-11-29T23:36:29.509+0800] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/azfarmustafa/airflow_tutorial/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/azfarmustafa/airflow_tutorial/dags/azfar_dag.py", line 40, in move_file_into_archive_folder
    source_blob_client = azure_hook.get_blob_client(container_name, source_blob_name)
AttributeError: 'WasbHook' object has no attribute 'get_blob_client'. Did you mean: '_get_blob_client'?
[2023-11-29T23:36:29.517+0800] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fantasy_premier_league_debug, task_id=move_file_into_archive_folder, execution_date=20231129T153625, start_date=20231129T153629, end_date=20231129T153629
[2023-11-29T23:36:29.536+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 28 for task move_file_into_archive_folder ('WasbHook' object has no attribute 'get_blob_client'; 24342)
[2023-11-29T23:36:29.575+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-29T23:36:29.589+0800] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
